### ISSUE TITLE
Add Support for the IBM JRE Memory calculation

### ISSUE THREAD

**Issue by bharathappali** [cloudfoundry/java-buildpack-memory-calculator#11]
Hi,

As the new JRE Component (IBM JRE) is added to the java buildpack, We have written a doc which explains about the vm options corresponding to IBM JRE which are not present in the current memory calculator. We would like to update the memory calculator to support IBM JRE by emitting these options.

You can find the [document here](https://docs.google.com/document/d/1a_U_UV8HMBMc4DUPxQ6N6hfdeJn9uD4N8SeXPm1gl90/edit?usp=sharing)

fyi - @ashu-mehra @dinogun

**Comment by glyn** [comment]
Thanks for raising this. Since I can't add comments to the document, I'll comment here.

1. I agree with the notion that the memory calculator needs extending to support the IBM JRE. Perhaps @nebhale would care to comment on this as the PM of the Java Buildpack and associated components.

2. It may be worth linking to [Java Buildpack Memory Calculator v3](https://docs.google.com/document/d/1vlXBiwRIjwiVcbvUGYMrxx2Aw1RVAtxq3iuZ3UK2vXA/edit#heading=h.uy41ishpv9zc) for context.

3. One of the goals of memory calculator v3 was to avoid the kernel occasionally killing the JVM process due to it exceeding the real memory limit in the container. The approach we took was to account for all the ways that the JVM can consume memory and then set explicit limits for each of them, with the limits adding up to the total memory available to the container. I wonder if this goal is achievable with the IBM JRE?

4. It will be necessary to determine an algorithm for calculating `-Xcodecachetotal`. The general approach we took was to measure the consumption of the various memory pools for a number of sample applications, observe close linear correlations to the number of loaded classes, and choose suitable constants for linear functions of the number of loaded classes (which is estimated by the Java buildpack and provided as an input to the memory calculation). However, for reserved code cache size, we found that the above approach resulted in high (20%) CPU consumption and so we made the calculation set the value to OpenJDK's default value (240 Mb on Java 8 and 48 Mb on Java 7). A similar approach may be necessary for `-Xcodecachetotal`.

5. Please could you say where any storage analogous to OpenJDK's metaspace is allocated from and how this is bounded. For instance, where are the read-only portions of classes ("ROM classes") allocated from?

6. I presume the IBM JRE's class sharing feature is not enabled in Cloud Foundry, but perhaps you could confirm this as it would affect the memory calcuation.

7. We need to agree how to differentiate between the openjdk-like JREs and the IBM JRE. It would be helpful to add this to the document, although it's a small detail and could wait until a Pull Request is created.

**Comment by ashu-mehra** [comment]
@glyn thanks for the quick response.

I agree with points 4 and 7.

>  where are the read-only portions of classes ("ROM classes") allocated from?

These are native memory allocations and IBM JRE does not provide any option to put an upper bound on it.

> I presume the IBM JRE's class sharing feature is not enabled in Cloud Foundry, but perhaps you could confirm this as it would affect the memory calcuation.

Yes, you are right. IBM JRE's class sharing is not enabled in Cloud Foundry.


Can you please provide some clarification on this statement:
> The approach we took was to account for all the ways that the JVM can consume memory and then set explicit limits for each of them, with the limits adding up to the total memory available to the container.

The memory calculator v3 takes into account various memory pools that JVM uses, but if I understand correctly, there would always be native memory allocations by JVM for its internal purpose which are not exposed externally. For example memory allocated by native code of class libraries, memory used by JVMTI agents etc. Such allocations can still cause kernel OOM killer to kick in.
Does it mean even when using memory calculator v3, it is not guaranteed that kernel would not kill the JVM process when memory consumption exceeds real memory in the container?

**Comment by glyn** [comment]
@ashu-mehra Yes, even with memory calculator v3, there is still a possibility of the JVM process exceeding its container memory limit and being killed, but the probability of this happening has been significantly reduced by setting limits for all the JVM's memory pools. If an application suffers from being killed OOM, a user can set some or all of the JVM's memory settings explicitly and/or increase the container's total memory.

So it seems that the IBM JRE will be at a disadvantage if it is not possible to account for and bound the memory used by classes. The probability of the JVM process being killed OOM will be higher than with OpenJDK.

Since the Java buildpack provides an estimate of the number of loaded classes, a potential workaround would be the memory calculation for the IBM JRE to allow some "spare" memory (by which I mean memory not included in JVM memory options) per class. This is a workaround rather than a proper solution because if the number of loaded classes is under-estimated or if an application's classes are larger than average, then the probability of the JVM process being killed OOM might still be undesirably high. In that case, a workaround by the user might involve setting some or all of the JVM's memory settings _and_ the container's total memory.

**Comment by nebhale** [comment]
@bharathappali and @ashu-mehra I’m leaning towards not including IBM’s memory calculation as part of this project.  The current memory-calculator is designed to be used with our default OpenJDK and OpenJDK-like (Oracle and Azure) JVMs.  The fact that the IBM JRE is _not_ OpenJDK-like (different memory pools, different memory usage profiles) means that we’d effectively need a big switch statement in the calculator as to whether we were calculating for OpenJDK or IBM.  If we’re effectively going to have two distinct code-paths, I think we should have two calculators completely.  This allows the IBM team to implement their own calculation strategy (which may be radically different from OpenJDK) and evolve it for their customers at a rate different than the OpenJDK version will evolve.

**Comment by ashu-mehra** [comment]
@nebhale I think your suggestion makes sense. Its better to have different calculator for IBM Java as there doesn't seem to be much common between OpenJDK and IBM Java when it comes to memory pools.
Just a question: I believe the cf containers use cgroups for controlling resources, and I read cgroups provide notification mechanism for memory pressure levels. Following is the text from cgroup/memory.txt in Linux kernel documentation on my system:

```
11. Memory Pressure

The pressure level notifications can be used to monitor the memory
allocation cost; based on the pressure, applications can implement
different strategies of managing their memory resources. The pressure
levels are defined as following:

The "low" level means that the system is reclaiming memory for new
allocations. Monitoring this reclaiming activity might be useful for
maintaining cache level. Upon notification, the program (typically
"Activity Manager") might analyze vmstat and act in advance (i.e.
prematurely shutdown unimportant services).

The "medium" level means that the system is experiencing medium memory
pressure, the system might be making swap, paging out active file caches,
etc. Upon this event applications may decide to further analyze
vmstat/zoneinfo/memcg or internal memory usage statistics and free any
resources that can be easily reconstructed or re-read from a disk.

The "critical" level means that the system is actively thrashing, it is
about to out of memory (OOM) or even the in-kernel OOM killer is on its
way to trigger. Applications should do whatever they can to help the
system. It might be too late to consult with vmstat or any other
statistics, so it's advisable to take an immediate action.

The events are propagated upward until the event is handled, i.e. the
events are not pass-through. Here is what this means: for example you have
three cgroups: A->B->C. Now you set up an event listener on cgroups A, B
and C, and suppose group C experiences some pressure. In this situation,
only group C will receive the notification, i.e. groups A and B will not
receive it. This is done to avoid excessive "broadcasting" of messages,
which disturbs the system and which is especially bad if we are low on
memory or thrashing. So, organize the cgroups wisely, or propagate the
events manually (or, ask us to implement the pass-through events,
explaining why would you need them.)

The file memory.pressure_level is only used to setup an eventfd. To
register a notification, an application must:

- create an eventfd using eventfd(2);
- open memory.pressure_level;
- write string like "<event_fd> <fd of memory.pressure_level> <level>"
  to cgroup.event_control.

Application will be notified through eventfd when memory pressure is at
the specific level (or higher). Read/write operations to
memory.pressure_level are no implemented.

Test:

   Here is a small script example that makes a new cgroup, sets up a
   memory limit, sets up a notification in the cgroup and then makes child
   cgroup experience a critical pressure:

   # cd /sys/fs/cgroup/memory/
   # mkdir foo
   # cd foo
   # cgroup_event_listener memory.pressure_level low &
   # echo 8000000 > memory.limit_in_bytes
   # echo 8000000 > memory.memsw.limit_in_bytes
   # echo $$ > tasks
   # dd if=/dev/zero | read x

   (Expect a bunch of notifications, and eventually, the oom-killer will
   trigger.)
```

Is there any way the cf containers can expose this to the application (like JVM) running inside the container and they can then register for "critical" pressure and generate OOM message before getting killed by the oom-killer?

**Comment by nebhale** [comment]
No it doesn't expose this information (it's consumed by Garden though).  The way we deal with it is that you can depend on `$MEMORY_LIMIT` being when the process starts.  You should use that to preemptively configure the JVM's memory pools in a way that works for most applications.  There are two goals for any memory calculator:

1.  The container OOM-killer should never kill a JVM.
  When the OOM-killer takes down a process it simply write `exit 137` to the console and emits no other metrics.  By ensuring that any out of memory situation (heap, meatspace, etc.) is first encountered by the JVM, better diagnostics can be emitted (simply identifying _which_ pool is exhausted is a huge improvement over the OOM-killer).  There's no way to guarantee this obviously (JVM's do allocate memory that cannot be bounded), but a memory calculator implementation should be able to come _very close_ to satisfying this requirement.
2.  Overriding the calculate values should be done with standard JVM options.
  So for example, if your calculator works out that meatspace should be 128M, but the user knows better about their application, that user should `cf set-env <APP> JAVA_OPTS '-XX:MaxMetaspaceSize=256M'` in order to override that value.  The calculator should then take the user configured value into account when conducting the calculation to ensure that #1 is still satisfied.

**Comment by ashu-mehra** [comment]
@nebhale I understand the purpose of memory calculator, and I have no questions on its purpose.

I was just wondering if memory pressure notification is made available to applications running inside the containers, it would help the applications to more accurately detect OOM condition and emit appropriate diagnostic data. Actually applications may even want to react to "low" or "medium" memory pressure as stated in the kernel doc I mentioned above.

Having said that, I acknowledge I am no authority in this area, and can't say for sure if it is even feasible for containers to expose this notification mechanism to the applications.

**Comment by glyn** [comment]
@julz Please could you comment on whether memory pressure notification is available to applications running inside Garden containers. I guess it comes down to what features of the memory cgroup are exposed inside the container. Thanks!

**Comment by glyn** [comment]
@ashy-mehra I think it's feasible for containers to notify applications of memory pressure, so the big question is whether this will be implemented in runC (and therefore in Garden). Maybe you'd like to discuss that with @julz since he looks after Garden.

**Comment by julz** [comment]
Hi all - sorry I missed this thread first time around! 

As of [garden-runc-release v1.9.4](https://github.com/cloudfoundry/garden-runc-release/releases/tag/v1.9.4) we do make the container's cgroups available in the container at `/sys/fs/cgroup`. It is, however, mounted read-only (for security reasons) so I don't think you'll be able to write to `/sys/fs/cgroup/memory/cgroup.event_control`. You should be able to use other features of the memory cgroup, though, such as inspecting `/sys/fs/cgroup/memory/memory.usage_in_bytes`.

**Comment by glyn** [comment]
Thanks @julz. So it seems the best solution that's implementable at the moment is for an application to _poll_ the memory pressure and act appropriately. @ashu-mehra - does that work for you?

**Comment by ashu-mehra** [comment]
As of now I don't have a strong use-case for applications to register for memory pressure notifications. I guess its not worth pursuing this at the moment.
@glyn @julz thanks for responding to my questions.

**Comment by glyn** [comment]
@ashu-mehra Can this issue be closed?

**Comment by ashu-mehra** [comment]
@glyn yes, I am fine with that. Please close it.
