### ISSUE TITLE
XX:MaxDirectMemorySize and Spring Cloud Stream with Kafka

### ISSUE THREAD

**Issue by odedia** [cloudfoundry/java-buildpack-memory-calculator#17]
We've been struggling with a lot of "Direct Memory Buffer" errors in some of our kafka-based spring cloud stream applications, running on PCF.

We noticed it mostly occurs while a single consumer is assigned multiple topic partitions.

```
018-02-05T18:26:30.178-06:00 [APP/PROC/WEB/4] [OUT] java.lang.OutOfMemoryError: Direct buffer memory
2018-02-05T18:26:30.179-06:00 [APP/PROC/WEB/4] [OUT] at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:71) ~[kafka-clients-0.10.1.1.jar!/:na]
2018-02-05T18:26:30.179-06:00 [APP/PROC/WEB/4] [OUT] at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:154) ~[kafka-clients-0.10.1.1.jar!/:na]
2018-02-05T18:26:30.179-06:00 [APP/PROC/WEB/4] [OUT] at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:135) ~[kafka-clients-0.10.1.1.jar!/:na]
2018-02-05T18:26:30.179-06:00 [APP/PROC/WEB/4] [OUT] at org.apache.kafka.common.network.Selector.poll(Selector.java:291) ~[kafka-clients-0.10.1.1.jar!/:na]
2018-02-05T18:26:30.179-06:00 [APP/PROC/WEB/4] [OUT] at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:232) ~[kafka-clients-0.10.1.1.jar!/:na]
2018-02-05T18:26:30.179-06:00 [APP/PROC/WEB/4] [OUT] at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:979) ~[kafka-clients-0.10.1.1.jar!/:na]

```

I believe this issue is related to the fact that the build pack assigns only 10 megabyes to the direct memory buffer, hardcoded.

With kafka using nio for all its processing, this can be the reason for our error.

I believe the buildpack should calculate the value for XX:MaxDirectMemorySize based on additional parameters, and if spring-cloud-stream-kafka-binder is in the classpath, it should increase the value.

**Comment by nebhale** [comment]
The problem with direct memory in the JVM is that it is both unbounded and there is no heuristic for determining a reasonable size. If we take your example of the Kafka binder as a heuristic, what value would you set it at? 100M, 1G?  Instead we’ve taken the approach that we’re going to put _some_ bound on it so that you can’t accidently allocate 1TB of direct memory in your container, but leave any changes to that value up to the discretion of each application developer. Running `cf set-env <APP> JAVA_OPTS ‘-XX:MaxDirectMemorySize=...’` will cause both the JVM and the memory calculator to do the right thing. The JVM will bound the size at your specified value and the memory calculator will reduce the allocated heap by that amount, leaving room in the container for it. 

I’m open to doing something more sophisticated if there are reliable size heuristics for certain libraries (e.g. the Kafka binder has a hard-coded limit to the amount of memory it will use) but since the Java community is (broadly) just getting started using Direct Memory, I don’t feel like we have a good idea of what to automatically allocate.

**Comment by odedia** [comment]
Thanks, that makes sense. It was my understanding the direct buffer memory is using the regular heap size as a point of reference for the max size, but I might be wrong.

I would however consider a slightly bigger value, since we noticed these errors in every testing environment with even low volume of message, so it seems 10M can't keep up once you move to the 20 partitions realm per instance (makes sense especially of a single instance listens on multiple topics). 

I agree 1gb is very high, but perhaps 64mb is a more reasonable starting point?

Also, it might not be for this forum but maybe Spring Cloud Stream documentation should point out this clear dependency while running on PCF.

Thanks again!

**Comment by nebhale** [comment]
The problem with any default choice of `MaxDirectMemorySize`, is that it's a heap memory penalty that _every single Java Application on Cloud Foundry_ must pay, regardless of whether they use direct memory or not.  So if we up it to 64M, which I agree seems like a perfectly reasonable number, most applications (which do not use direct memory at this point) would end up losing 10% of their minimum container size (~650M with default JVM configuration).  And this is the tension we run into; do we optimize for the users who aren't using Kafka or the ones that are?  How much a penalty do the hundreds of thousands of Java instances pay for the minuscule (but admittedly growing) number of Kafka-related instances.  I'm totally open to changing this default in the future, but at the moment, the number of people required to change that value is so small compared to the total number of Java instances on CF, I think we've got the default correct for today.

I do agree that Spring Cloud Stream should call this out directly.  In fact, they should talk about bounding this value in **all** containerized environments since it is both likely to grow beyond the bounds of a container and has poor visibility at runtime.

**Comment by odedia** [comment]
Sounds good. I’ll close this issue and open another in cloud stream. 

Thanks!

**Comment by nebhale** [comment]
@odedia Thanks for the great discussion.  Something tells me that I'll be linking to this issue repeatedly in the future.

**Comment by odedia** [comment]
No problem, thank you as well!
For reference, I opened the following issue in spring cloud stream:

https://github.com/spring-cloud/spring-cloud-stream/issues/1226
