### ISSUE TITLE
Adjust ReservedCodeCacheSize

### ISSUE THREAD

**Issue by Xerus2000** [cloudfoundry/java-buildpack-memory-calculator#28]
I have a very small application, and the ReservedCodeCacheSize of 240M is not appropriate and stealing the heap that I need. You can configure some things with the Environment variable, but I didn't see any way to tweak this parameter, or change the Java Parameters directly.

**Comment by nebhale** [comment]
240M is the default size the JVM chooses (we reflect that since without opinion).  In order to change it, you should set the standard JVM flag (`cf set-env JAVA_OPTS '-XX:ReservedCodeCacheSize=...'`).  This recommendation comes along with the standard warnings about the likely performance decrease of your application.
